# Generated by Django 5.2.6 on 2025-09-21 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
