# Generated by Django 5.2.6 on 2025-09-21 07:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_remove_reservaareacomun_created_at_and_more'),
        ('condominio', '0002_remove_property_email_remove_property_propietario_and_more'),
        ('payments', '0002_remove_payment_created_at_remove_payment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='description',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='priceconfig',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='priceconfig',
            name='currency',
            field=models.CharField(default='BOB', max_length=8),
        ),
        migrations.AddField(
            model_name='priceconfig',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='commons.reservaareacomun'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=12)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL)),
                ('price_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.priceconfig')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='condominio.property')),
            ],
            options={
                'db_table': 'payments_charge',
                'ordering': ['-issued_at', '-fecha_pago', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.charge'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation__isnull', False), ('charge__isnull', True)), models.Q(('reservation__isnull', True), ('charge__isnull', False)), _connector='OR'), name='payment_target_exactly_one'),
        ),
    ]
