# Generated by Django 5.2.6 on 2025-09-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='priceconfig',
            name='updated_at',
        ),
    ]
