# Generated by Django 5.2.6 on 2025-09-13 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'Mantenimiento'), ('CERRADO', 'Cerrado')], default='DISPONIBLE', max_length=20)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
            ],
            options={
                'db_table': 'areacomun',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('horario_apertura__lt', models.F('horario_cierre'))), name='area_horario_apertura_menor_cierre')],
            },
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='commons.areacomun')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva_areacomun',
                'ordering': ['-fecha_reserva', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='res_hora_inicio_menor_fin')],
            },
        ),
    ]
