# Generated by Django 5.2.6 on 2025-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaareacomun',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='approved_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
