# Generated by Django 5.2.6 on 2025-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=1)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('propietario', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible')], default='disponible', max_length=20)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'property',
                'ordering': ['edificio', 'numero'],
            },
        ),
    ]
