# Generated by Django 5.2.6 on 2025-09-20 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='property',
            name='telefono',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PropertyTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='condominio.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_tenant',
                'indexes': [models.Index(fields=['property', 'user'], name='property_te_propert_180e0c_idx')],
                'unique_together': {('property', 'user')},
            },
        ),
    ]
