# Generated by Django 5.2.6 on 2025-09-19 22:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('asignar_a', models.CharField(choices=[('interno', 'Personal Interno'), ('externo', 'Personal Externo')], default='interno', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad', models.CharField(max_length=100)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='maintenance.reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('asignar_a', models.CharField(choices=[('interno', 'Personal Interno'), ('externo', 'Personal Externo')], default='interno', max_length=10)),
                ('fecha_programada', models.DateField()),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ubicacion', models.CharField(max_length=200)),
                ('asignado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
