# Generated by Django 5.2.6 on 2025-09-27 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_image_id', models.CharField(max_length=128, unique=True)),
                ('face_id', models.CharField(db_index=True, max_length=128)),
                ('collection_id', models.CharField(max_length=128)),
                ('s3_key', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked'), ('pending', 'pending')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_userface',
            },
        ),
    ]
