# Generated by Django 5.2.6 on 2025-09-28 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userface',
            name='collection_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userface',
            name='external_image_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userface',
            name='face_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userface',
            name='s3_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userface',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='userface',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userface',
            table=None,
        ),
    ]
