# Generated by Django 5.2.6 on 2025-09-28 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_userface_collection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userface',
            name='collection_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userface',
            name='external_image_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userface',
            name='face_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userface',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userface',
            name='status',
            field=models.CharField(default='registered', max_length=32),
        ),
        migrations.AlterField(
            model_name='userface',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userface',
            unique_together={('user', 'collection_id')},
        ),
        migrations.AlterModelTable(
            name='userface',
            table='ai_userface',
        ),
    ]
