# Generated by Django 5.2.6 on 2025-09-28 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_userface_collection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='registered', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_plate',
            },
        ),
    ]
