# Generated by Django 5.2.6 on 2025-09-28 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together={('number', 'user')},
        ),
        migrations.AlterField(
            model_name='plate',
            name='number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='plate',
            name='s3_key',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='status',
        ),
    ]
