# Generated by Django 5.2.6 on 2025-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_plate_unique_together_alter_plate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dog_loose', 'Perro suelto'), ('vehicle_seen', 'Vehículo visto')], max_length=32)),
                ('camera_id', models.CharField(blank=True, max_length=64, null=True)),
                ('s3_video_key', models.CharField(max_length=512)),
                ('s3_image_key', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp_ms', models.BigIntegerField()),
                ('confidence', models.FloatField(default=0.0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_alerts',
                'indexes': [models.Index(fields=['type', 'created_at'], name='ai_alerts_type_2dee19_idx')],
            },
        ),
    ]
