# Generated by Django 5.2.6 on 2025-09-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alert_retype_vehicle_seen_to_bad_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('dog_loose', 'Perro suelto'), ('dog_waste', 'Perro haciendo necesidades'), ('bad_parking', 'Vehículo mal estacionado')], max_length=32),
        ),
    ]
