# Generated by Django 5.2.6 on 2025-09-28 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=16)),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_visitor_event',
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='ai_visitor__user_id_25cf11_idx')],
            },
        ),
    ]
