# Generated by Django 5.2.6 on 2025-09-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_visitorevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('similarity', models.FloatField(default=0.0)),
                ('s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('event_type', models.CharField(default='session', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_visitor_session',
            },
        ),
        migrations.DeleteModel(
            name='VisitorEvent',
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['user', 'login_at'], name='ai_visitor__user_id_ff7291_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['user', 'logout_at'], name='ai_visitor__user_id_f20755_idx'),
        ),
    ]
