# Generated by Django 5.2.6 on 2025-09-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='nombre',
        ),
    ]
