# Generated by Django 5.2.6 on 2025-09-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_remove_bitacora_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='hora_entrada',
            field=models.TimeField(),
        ),
    ]
